### ISSUE TITLE
Accounts return 403 unauthorized

### ISSUE THREAD

**Issue by niklavs-raudseps** [lunarway/openbanking#11]
Hello,

I was able to get an access token in sandbox, but I wasn't able to use it when accessing accounts.
```
curl --location --request GET 'https://sandbox.openbanking.prod.lunar.app/aisp-pisp/accounts' \
--header 'Authorization: Bearer ACCESS_TOKEN' \
--header 'X-Request-ID: REQUEST_ID'
```
```
{
    "code": 403,
    "message": "unauthorized"
}
```

I don't want to add any more information for security reasons, but hopefully this should suffice.

**Comment by niklavs-raudseps** [comment]
Yes, it turns out I wasn't using the correct scope. I changed it to `PSP_AI`, but now I can't get a refresh token. Does this mean that I cannot get a refresh token?

**Comment by Crevil** [comment]
You need to register for both `PSP_AI` and `offline` if you want the refresh token.

See https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/#refresh-tokens for more details 😄

**Comment by niklavs-raudseps** [comment]
How can I change my scopes then if I'm already registered? I don't see any endpoint that allows me to do that.
