### ISSUE TITLE
Small questions

### ISSUE THREAD

**Issue by niklavs-raudseps** [lunarway/openbanking#12]
I have a few questions

1. I want to use the `offline` scope so I can get refresh tokens, but I need to change my registration for this. Is there a PUT/PATCH request to do this? There is only an endpoint for changing the redirect-uri.
2. How long in the past are transactions able to be retrieved?
3. Do transactions have a `dateTo`, `dateFrom` paramater?

**Comment by niklavs-raudseps** [comment]
Hey, has somebody read this?

**Comment by dentych** [comment]
Hey @niklavs-raudseps 

I can't answer your question 1, maybe you can help here @Crevil ?

All transactions for an account can be retrieved, using the endpoints specified in https://developer.openbanking.prod.lunar.app/catalog/default/api/aisp-pisp . You can use the limit/offset parameters to retrieve it.

I'm not entirely sure what you mean with dateTo and dateFrom, can you elaborate a little? Transactions have a transactionTime. Transaction time will be put on all transactions, for when they happened, and postingTime will be different from null once the transaction has been posted to the account. When it's not null, it is likely a reservation or hasn't been posted yet.

**Comment by Crevil** [comment]
It is currently not possible to update the scopes after regitration. Have you registered in the sandbox or live environment?

**Comment by niklavs-raudseps** [comment]
1. Yes, I have registered without the offline scope for both sandbox and production.
2. `dateTo` and `dateFrom` means we request transactions from a certain time period (say from November to December). We want this since the End User Agreement our clients signs says that we won't send transactions older than 90 days. If we store those old transactions than we will have broken that agreement.

**Comment by niklavs-raudseps** [comment]
How long should I wait until an update which allows me to change my registration scopes?

**Comment by Crevil** [comment]
@hoeg do you have an idea on a timeline for this?

**Comment by dentych** [comment]
@niklavs-raudseps Currently there is only limit/offset capability in the API, not from and to dates.

**Comment by niklavs-raudseps** [comment]
When will I be able to change my registration?

**Comment by bsnlunar** [comment]
Hi niklavs-raudseps 
This is now placed into our back log - but we cannot at present time give you a timeframe for solving this feature request covering to and from dates

**Comment by niklavs-raudseps** [comment]
@bsnlunar The date_to and date_from params would be great, but they are not strictly necessary. When will I be able to change the scopes in my registration? Because that to me is the most important thing.

**Comment by niklavs-raudseps** [comment]
@bsnlunar Any progress on this issue?

**Comment by bsnlunar** [comment]
Hi @niklavs-raudseps 
We are still having this on our backlog in the Squad involved. But no current progress that will benefit you can yet be promised.

**Comment by niklavs-raudseps** [comment]
Well, then add this as a priority.

**Comment by niklavs-raudseps** [comment]
Hello,

Any progress here?

**Comment by TechHolm** [comment]
Hi, @niklavs-raudseps 
Apologies for the late answer.
We currently do not have any updates on the issue. We will get back to you as soon as we have any updates of interest.

Br. Lunar

**Comment by Crevil** [comment]
I'm cleaning up old issues and acknowledge this feature is still missing.

To stay updated please subscribe to https://github.com/lunarway/openbanking/issues/53 going forward.
