### ISSUE TITLE
Some transactions have "1970-01-01T00:00:00Z" postingTime value and DKK -> DKK currencyExchange

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#14]
As in the title - this happened e.g. today for the request at `Tue, 16 Nov 2021 09:16:11 GMT`
The currency conversion in the response was the following:
```json
"currencyExchange": {
   "currency": "DKK",
   "exchangeRate": 1,
   "targetCurrency": "DKK"
},
```
Is such payload is intentional? Or should it be `null` when there is no currency conversion?

**Comment by dentych** [comment]
Hey @mbospiir .

Can you please email me the transaction ID with this currencyExchange, and also for the postingTime = 1970xxx ? Thank you 🙏 

Same email address as last 😄

**Comment by mbospiir** [comment]
@dentych sent

**Comment by mbospiir** [comment]
Hi @dentych, could you please update us on the status of this ticket?

**Comment by dentych** [comment]
I put a fix for this in production, so you should no longer see these issues.

I'm looking into the duplicate fields still, as it doesn't seem to be fixed. Will reply on the other issue once it's fixed.
