### ISSUE TITLE
Some accounts are missing balance info

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#15]
@dentych we didn't have to wait that long ;)
It happened for a response from `Tue, 16 Nov 2021 15:33:47 GMT` (`Date` header) - 3 out of 6 accounts do not have balance information.

**Comment by dentych** [comment]
Looking into it!

**Comment by dentych** [comment]
Can you email me the response or alternatively the account IDs missing balance to dty at lunar.app? My modification from a few days ago didn't quite make it to production 😬 It is now, though. But for this call I need some IDs to investigate further.

Sorry for the inconvenience

**Comment by mbospiir** [comment]
@dentych sure, sent

**Comment by dentych** [comment]
Hey. I deployed a fix which should return balances for the accounts. It was disregarded for accounts with balance = 0, because Go's default value deemed that "null".

I deployed a fix to production. I'll close the issue as resolved =)
