### ISSUE TITLE
Duplicate transaction ids still an issue

### ISSUE THREAD

**Issue by micspiir** [lunarway/openbanking#17]
Last week we reported an issue with duplicate transaction ids (#16). We still see this issue.

You reported that you deployed a fix on November 18, but we basically haven't seen any change in the number of duplicates that we receive from you.

This is currently blocking us from using your PSD2 interface, and we have clients that have many transactions deleted because of the way different systems handle duplicate ids.

Let me know if you need more data to investigate this.

**Comment by micspiir** [comment]
It looks like this has improved since Tuesday at 12.00. We still see some duplicates, but we have seen a sharp drop in the amount of duplicates.

**Comment by micspiir** [comment]
Correction: actually we still see the issue persists unchanged. It just looked like it was improving, but that was because we have been making much fewer calls to you since Tuesday, because of this issue.

**Comment by dentych** [comment]
Hello. This should now be actually fixed. Both for accounts and transactions. I noticed it was a problem in both places.

**Comment by micspiir** [comment]
@dentych From our systems this also seems to be solved now. Thank you very much.
