### ISSUE TITLE
Payment initiation authorisation gets timed out immediately

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#18]
Hi,
we are testing PIS on production and when trying to authorize a domestic transfer with the following id: `93492d20-cfd5-4dc2-bfdf-fb45f409bd71` (from `Fri, 03 Dec 2021 11:28:01 GMT`) the flow looks like that (from the PSU perspective):

1. I type in SSN in browser
2. I open a push notification on my phone and approve access with touch id
3. I choose my account in my browser
4. I get a new approval request on my phone but it has an error saying that “Time has run out. The payment was rejected. The payment was rejected because you did not approve it in time”. Meanwhile the timer in the browser is still going with like 4 mins left.

We have a phone screen recording of this case if you need it.

**Comment by dentych** [comment]
Was this an instant transfer or not?

**Comment by mbospiir** [comment]
@dentych it was a normal transfer (`Instant: false`).
The payment date was unspecified.

**Comment by dentych** [comment]
Alright. That makes sense. I could reproduce it that way too, just wanted to make sure :)
I'm working on a fix 😄

**Comment by dentych** [comment]
A fix has been deployed to production. You should now be able to send a call with immediate = false and no date, and it should be set to payment date today.
