### ISSUE TITLE
OAuth2 flow results with "The request is not allowed. No CSRF value available in the session cookie."

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#2]
Hi,
upon successful sandbox TPP registration, I'm trying to get an access token. I send the following request:
```
https://auth.sandbox.openbanking.prod.lunar.app/oauth2/auth?redirect_uri=[redacted]&client_id=[redacted]&response_type=code&scope=PSP_AI&state=[random-GUID]
```
In response, I get a `Location` header, which I paste into the browser and then, after clicking the *Submit* button, I get redirected to my redirect URL with query params indicating an error:
`error=request_forbidden&error_description=The+request+is+not+allowed.+No+CSRF+value+available+in+the+session+cookie.&state=6ee94a47-cf55-4b13-9bb1-3d4040c29360`

The */oauth2/auth* request is done in the backend, while the redirect URL is presented on the PSU side, so obviously, there are no cookies there.

**Comment by Crevil** [comment]
Thank you for adding context 🙏 

I will get back to you about that cookie 👍 

You are right about the `client_secret_post` method. That is misleading. 

We currently only support the `client_secret_basic` method. This is mainly due to the recommendations of the [OAuth2 RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1).

Are you limited by this or is it enough to make the docs more clear? Also the `openid-configuration` endpoint should reflect this ofc.

**Comment by mbospiir** [comment]
Thank you for considering changing that.
We do not seem to be limited, but the thing is that the *start auth* request now needs to be executed in the PSU's browser, so we need to pass over there the whole URL containing e.g. our `client_id`. Would be best to keep such variables in the backend only.

**Comment by Crevil** [comment]
I'm unsure I follow your response as we have a couple of questions open.

Can I get you to clear it up for me?

1) The `start auth` flow needs to be started in the PSU's browser: As far as I can see in our setup this looks to be a hard requirement. The `client_id` is generally to be considered public as far as I know. Can you point me to something that argues for keeping it 'backend only'?

2) The `oauth2/token` endpoint requires `client_secret_basic`. Does this limitation impose issues for you?

Thanks in advance 🙏

**Comment by mbospiir** [comment]
1. Yes, `client_id` is public and thus sent in the query parameters. Just wanted to keep the complexity and variables in the backend as a principle - where we have control over what's going on. But as it is clear now that the `start auth` call originating from the PSU works just fine and does not require setting any cookies, it's totally alright.
2. No, it's ok. Just the flow chart is misleading in the documentation, as it shows the `client_secret_post` method.

**Comment by Crevil** [comment]
Thank you for clearifying @mbospiir . The flow chart on `start auth` is now updated to reflect this and I'll make sure to do the same for the `client_secret_post`.

**Comment by Crevil** [comment]
For the record the docs are now updated with a warning on the incorrectness of the well-known endpoint.
https://developer.openbanking.prod.lunar.app/docs/default/API/Registration/access_token/
