### ISSUE TITLE
Stays on /aisp-pisp/polling after payment approval

### ISSUE THREAD

**Issue by christianpanton** [lunarway/openbanking#20]
We are stuck at this screen in the payment journey: /aisp-pisp/polling 

![image](https://user-images.githubusercontent.com/392398/145420953-91cc297c-22bf-4332-a6cb-cb5930ee24fb.png)

The payment have been approved in the Lunar app, but control is not returned to us.

The endpoint /aisp-pisp/polling/<id>/status returns status: AWAITING_APPROVAL to the front-end after approval.

**Comment by bsnlunar** [comment]
thank you We will look into this

**Comment by Kledal** [comment]
Hi @christianpanton,

Can you try again and verify that it works now?

**Comment by christianpanton** [comment]
Yes, redirection works now. We have another error after this in the flow, but will reach out separately for that.
