### ISSUE TITLE
TPP registration endpoint

### ISSUE THREAD

**Issue by GvidasPranauskasKevin** [lunarway/openbanking#24]
Hello,

I have been trying to find the registration endpoint on Lunar Open Banking developer portal, but got no luck (https://developer.openbanking.prod.lunar.app/docs/default/API/Registration). When opening this Link, 404 Not Found error page is displayed, thus I am not able to proceed with the registration.

Could you help accessing the registration documentation?

**Comment by Crevil** [comment]
Looking into it now 🙏

**Comment by Crevil** [comment]
The document is available again. Thank you for reporting 🙏
