### ISSUE TITLE
Owner account name on account information requests

### ISSUE THREAD

**Issue by micspiir** [lunarway/openbanking#25]
Your customers are very eager to get access to the name of the owner of an account through the PSD2 interface.

Currently we don't get that, when calling https://openbanking.prod.lunar.app/aisp-pisp/accounts for a client.

Could you share with us when we would be able to provide that to the clients?

**Comment by bsnlunar** [comment]
I will ensure we get this into our engineering squads backlog

**Comment by micspiir** [comment]
Thank you for the update. Will you keep us updated here in this ticket once this is scheduled?

**Comment by TechHolm** [comment]
Hi, @micspiir 
We currently do not have any updates on this issue. We will get back to you in this ticket as soon as we have any updates of interest.

Br. Lunar

**Comment by Palun** [comment]
@Crevil Would you be able to find us an update also on this issue?

Thanks

Patrik

**Comment by dentych** [comment]
We've looked further into this, and is planning to add the account holder name to the API sometime in course of Q4.

**Comment by Palun** [comment]
@dentych Thanks for the update!

**Comment by jejaiia** [comment]
Hi @dentych, 
When should we expect the field available during Q4?

**Comment by dentych** [comment]
Apologies for the 🐌 speed. We had a few problems when implementing the account owner, so it's taking a little longer than anticipated. We are almost finished, though, so the wait shouldn't be too long. I'll still update you when it has been deployed 😬

**Comment by dentych** [comment]
This should now be fixed, and account owner name should be part of the GET accounts response 👍 

Sorry for the delay!
