### ISSUE TITLE
Documentation - Error message

### ISSUE THREAD

**Issue by annaremaeus** [lunarway/openbanking#27]
Hi,

When looking at your documentation website there is the following error message: 
"Building a newer version of this documentation failed. Error: "Failed to generate docs from /tmp/backstage-pIIILF into /tmp/techdocs-tmp-aPMpdj; caused by unknown error 'Command mkdocs failed, exit code: 1'"

We wonder why it's there and if you're planning on realeasing a new version of the documentation, when will it be available?

Looking forward to hearing back from you!

**Comment by Crevil** [comment]
Thank you for reaching out. This is a known bug and it shouldn't impact the correctness of the docs.

We are however tracking it and will release a fix at some point 👍

**Comment by annaremaeus** [comment]
Hi Crevil,

Thank you for your swift response! Good to know about the error message.

Can I take this opportunity to ask some general questions about your PSD2 API?

- What are the supported authentication methods?
- How does background refreshes work?
- What is your transaction history availability?
- How do you return account types? Is it one endpoint for all accounts, if yes how can they be distinguished, or is it with a separate endpoint for each product?

Let me know if you want these questions in a separate ticket.

**Comment by Crevil** [comment]
Hopefully most of these details are documented in https://developer.openbanking.prod.lunar.app/home and if not, please create separate tickets so the responsible teams can get an answer for you 🙏

**Comment by annaremaeus** [comment]
Unfortunately I can't fin this information in the documentation so I'll create a separate ticket. Thanks again for your help!
