### ISSUE TITLE
API questions 

### ISSUE THREAD

**Issue by annaremaeus** [lunarway/openbanking#28]
Hi,

I can't seem to find the answers to these general questions about your PSD2 API and would therefore appreciate getting, would highly appreciate if you could help me answer them.

- What are the supported authentication methods?
- How does background refreshes work?
- What is your transaction history availability?
- How do you return account types? Is it one endpoint for all accounts, if yes how can they be distinguished, or is it with a separate endpoint for each product?

Looking forward ot your answer!

Best,
Anna

**Comment by annaremaeus** [comment]
Hi, do you have any answers to the questions above?

**Comment by TechHolm** [comment]
Hi @annaremaeus 
Apologies for the late delayed.
I have talked to the responsible squads in Lunar that can provide answers to your questions:

Q: What are the supported authentication methods?
A: Standard OpenID Connect flow with mTLS

Q: How does background refreshes work?
A: It is a standard openid connect flow so you should have a refresh token that you can use to call the standard /token endpoint

Q: What is your transaction history availability?
A: No limit

Q: How do you return account types? Is it one endpoint for all accounts, if yes how can they be distinguished, or is it with a separate endpoint for each product?
A: We only return one type. Payment accounts. That is what PSD2 only covers.

Hope you find these answers sufficient

Br. Lunar
