### ISSUE TITLE
Access token API question

### ISSUE THREAD

**Issue by fonzi0711** [lunarway/openbanking#35]
Hi Lunar team !

We would like to start using Lunar production (live) APIs. We checked the documentation and there is mention of a "Get status" step on the authentication/authorization flow : https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/ 
I'm not sure to follow the whole flow. I wonder if we need to pull the status from your side or not ? If so, what's the endpoint and the parameters ?

Thanks in advance

**Comment by hoeg** [comment]
We are serving the page that handles that. Notice that the get status call follows a redirect we are making and the call is between the User and Lunar, your service is not involved in this part of the login flow.
