### ISSUE TITLE
AISP - transaction list

### ISSUE THREAD

**Issue by violetaionita-mastercard** [lunarway/openbanking#38]
Hello, 

Kindly ask you to give us more details on which transactions are returned when called the API /aisp-pisp/accounts/{accountId}/transactions without filling in the From/To parameters? We are interested in knowing which is the period from when the transactions are. 

What is the behavior when the parameters From/TO are set?

Thank you, 
Violeta 
Mastercard Open Banking

**Comment by violetaionita-mastercard** [comment]
Hello, 

Could you please check our questions and provide more details? We have a customer that is asking daily about our functionality and we can not replay to him without these details. 

Thank you, 
Violeta

**Comment by violetaionita-mastercard** [comment]
Hello,

Did you have an opportunity to look into this? Could you provide ETA? 

Thank you, 
Violeta

**Comment by JensMagnus** [comment]
Hi

If the API is called without _from_ and _to_ we return an X amount of newest transactions

If _from_ or _to_ transactions from within those limits are returned;

If to is set, transactions BEFORE that limit is returned

If from is set, the same applies for when it isn't, unless there's less than X amount of transactions

Hope that makes sense :)

**Comment by violetaionita-mastercard** [comment]
Hello, 

We have a case where the response to the end point https://openbanking.prod.lunar.app/aisp-pisp/accounts/4c705[redacted]1ee9/transactions?offset=0&limit=100 have returned 24 transactions,  even though we asked for a limit of 100. 

Could you please let me know how many transactions maximum we can get in a call? And why we didn't get the last 100 transactions? And also if we were to use date from would it result in getting more transactions?

Thank you, 
Violeta

**Comment by JensMagnus** [comment]
We allow a maximum of 500 transactions to be returned for each call.

**Comment by violetaionita-mastercard** [comment]
The call to the endPoint https://openbanking.prod.lunar.app/aisp-pisp/accounts/4c705[redacted]1ee9/transactions?offset=0&limit=100 have returned 24 transactions. Why were there received just 24 transactions? The user has confirmed that he has more older transactions.  Why we didn't get the last 100 transactions?

**Comment by violetaionita-mastercard** [comment]
Hi JensMagnus, 

Could you please provide more details on my questions from above?

Thank you, 
Violeta

**Comment by violetaionita-mastercard** [comment]
Hello,

Did you have an opportunity to look into this? Could you provide ETA?

Thank you,
Violeta

**Comment by JensMagnus** [comment]
Hi.

I looked into the data and it seems there might be an issue somewhere. I'll have to investigate further, and put it on our task board for the coming weeks.

Br,

**Comment by violetaionita-mastercard** [comment]
Hi JensMagnus,

Could you please provide an update on this issue? Did you managed to identify something on Lunar side?

Thank you, 
Violeta

**Comment by JensMagnus** [comment]
I believe we have identified the problem. We'll take a look, but I can't give an estimate.

**Comment by violetaionita-mastercard** [comment]
Hello,

Do you have any estimate on the problem identified ?

Thank you, 
Violeta

**Comment by violetaionita-mastercard** [comment]
Hello, 

Do you have any updates on this issue?

Thank you, 
Violeta

**Comment by JensMagnus** [comment]
Do you experience the problem for other users? I've tried to recreate the problem, which I didn't succeed in.

**Comment by violetaionita-mastercard** [comment]
Hello, 

No other user has reported it. 
The user that initially has reported the issue informed us that they no longer have Lunar, as they have switched banks.

Thank you, 
Violeta

**Comment by JensMagnus** [comment]
I'll close the case for now, but let me know if you see similar behaviour again.
