### ISSUE TITLE
Is there any way for the TPP to specify the country

### ISSUE THREAD

**Issue by Agachily** [lunarway/openbanking#39]
Hi, on the bank authentication page, we see there is a button to switch country. As shown follows:

<img width="1439" alt="Screen Shot 2023-02-07 at 10 20 38 AM" src="https://user-images.githubusercontent.com/89035736/217190261-f46b47e3-91e9-4f1e-9ec4-2e6f4f9e2076.png">

We wonder is there any way for the TPP to specify the country to be used through certain parameter?

**Comment by Crevil** [comment]
The nationality parameter enables you to prepopulate the selector, eg. setting `?nationality=se` will set the selection on the page to SE.
