### ISSUE TITLE
OAuth2 auth request with `offline` scope fails

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#4]
Hi,
the initial OAuth2 call fails when trying to use `offline` scope mentioned in the other issue.
```
curl --location --request GET 'https://auth.sandbox.openbanking.prod.lunar.app/oauth2/auth
   ?redirect_uri=<REDIRECT_URI>
   &client_id=<CLIENT_ID>
   &response_type=code
   &scope=PSP_AI%20PSP_PI%20offline
   &state=<GUID>'
```
It redirects to:
`<CALLBACK_URI>?error=invalid_scope&error_description=The+requested+scope+is+invalid%2C+unknown%2C+or+malformed.+The+OAuth+2.0+Client+is+not+allowed+to+request+scope+%27offline%27.&state=<GUID>`

I also tried `&access_type=offline` but still - no `refresh_token` is being returned.
Comma-delimited scopes as in the documentation - [here](https://developer.openbanking.prod.lunar.app/docs/default/API/Registration/access_token/), see first interaction diagram - does not work as well.

**Comment by Crevil** [comment]
The OAuth2 specification specifies scopes to be space separated values: https://datatracker.ietf.org/doc/html/rfc6749#section-3.3

So the docs are in this case misleading. I will make sure to update that.

Further more a bug prevents you from requesting that specific scope. I'll let you know when it is fixed. It should be done shortly.

**Comment by Crevil** [comment]
Fix is out now. Please register a new test TPP in sandbox and try again. 🙏
