### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by 2dete** [lunarway/openbanking#41]
While try to registering for sandbox/production environments i am getting 500 error in postman without any error message
Tried to run curl and here is request with response :  

curl --location --request POST 'https://openbanking.prod.lunar.app/tpp/register' \
--header 'X-Request-ID: 36938a1c-2fa1-43a2-ba9b-ab8fccc30234' \
--header 'Content-Type: application/json' \
--data-raw '{
    "redirectUris": [
        "https://ob.nordigen.com/psd2/oauth/lunar/code/",
        "https://ob.gocardless.com.com/psd2/oauth/lunar/code/"
    ],
    "roles": [
        "PSP_AI",
        "PSP_PI"
    ]
}' --cert "[MASKED]qwac.pem" --key "[MASKED]qwac.key" -k -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 34.253.31.18:443...
* Connected to openbanking.prod.lunar.app (34.253.31.18) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Request CERT (13):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=openbanking.prod.lunar.app
*  start date: Apr  9 08:39:02 2023 GMT
*  expire date: Jul  8 08:39:01 2023 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: POST]
* h2h3 [:path: /tpp/register]
* h2h3 [:scheme: https]
* h2h3 [:authority: openbanking.prod.lunar.app]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* h2h3 [x-request-id: 36938a1c-2fa1-43a2-ba9b-ab8fccc30234]
* h2h3 [content-type: application/json]
* h2h3 [content-length: 209]
* Using Stream ID: 1 (easy handle 0x13d80bc00)
> POST /tpp/register HTTP/2
> Host: openbanking.prod.lunar.app
> user-agent: curl/7.87.0
> accept: */*
> x-request-id: 36938a1c-2fa1-43a2-ba9b-ab8fccc30234
> content-type: application/json
> content-length: 209
> 
* We are completely uploaded and fine
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500 
< date: Mon, 15 May 2023 12:29:21 GMT
< content-length: 0
< strict-transport-security: max-age=15724800; includeSubDomains; preload
< 
* Connection #0 to host openbanking.prod.lunar.app left intact
Tried to add certs in a different format but got the same results.
Checked certs via /tpp/verify/
and got 200 so certs are good.
Is there anything else i am missing ?

**Comment by Crevil** [comment]
The registration flow has been updated since this issue was created.

Please see the latest updated docs and try again: https://developer.openbanking.prod.lunar.app/docs/default/api/registration/register/

As the provided information here is outdated, please open another issue if registration issues persist.
