### ISSUE TITLE
404 on accounts endpoint

### ISSUE THREAD

**Issue by Palun** [lunarway/openbanking#43]
I just tested our integration again and now I have started getting 404 on the accounts endpoint. This same call worked last week so I am a bit confused. Can you help me figure out what is wrong?

Thanks 

Patrik

2 * Client out-bound request
2 * 2023-06-22--10:48:58.033+0000
2 > GET https://openbanking.prod.lunar.app/aisp-pisp/accounts
2 > Authorization: Bearer MASKED
2 > Accept: application/json
2 > User-Agent: Tink (+https://www.tink.se/; [noc@tink.se](mailto:noc@tink.se))
2 > X-Aggregator: Tink Testing
2 * Client in-bound response
2 * 2023-06-22--10:48:58.033+0000
2 < 404
2 < Cache-Control: must-revalidate,no-cache,no-store
2 < Server: Jetty(9.4.50.v20221201)
2 < Content-Length: 70
2 < Content-Type: application/json
{
"message":"Not Found",
"url":"/aisp-pisp/accounts",
"status":"404"
}

**Comment by Crevil** [comment]
Hi @Palun 

We are unable to identify your failing request on our end.

Can I get you to verify that the correct information is provided in this issue? Preferably by attempting again to avoid any temporary issues being the cause of the 404 response.

**Comment by Palun** [comment]
Hi @Crevil ! 

Thanks for reaching out. I just made another attempt with the same result - what would you need to identify the request?

POST https://auth.openbanking.prod.lunar.app/oauth2/token?redirect_uriMASKED
1 > Authorization: Basic MASKED
1 > Accept: application/json
1 > X-Request-Id: 12c22c41-85ae-4c90-915e-5cf848745c1c
1 > X-Signature: MASKED
1 > Connection: Keep-Alive
1 > User-Agent: Tink (+https://www.tink.se/; noc@tink.se)
1 > X-Aggregator: Tink Testing
1 > Host: auth.openbanking.prod.lunar.app
1 > Accept-Encoding: gzip,deflate
1 > Content-Length: 265
1 > X-Signature-Info: Visit https://cdn.tink.se/aggregation-signature/how-to-verify.txt for more info.
1 > Content-Type: application/x-www-form-urlencoded
code=MASKED&grant_type=authorization_code&client_id=MASKED1&redirect_uri=https%3A%2F%2Fapi.tink.se%2Fapi%2Fv1%2Fcredentials%2Fthird-party%2Fcallback

1 * Client in-bound response
1 * 2023-07-04--07:36:33.216+0000
1 < 200
1 < Strict-Transport-Security: max-age=15724800; includeSubDomains; preload
1 < Cache-Control: no-store
1 < Connection: keep-alive
1 < Pragma: no-cache
1 < Content-Length: 291
1 < Date: Tue, 04 Jul 2023 07:36:33 GMT
1 < Content-Type: application/json;charset=UTF-8
{"access_token":"MASKED","expires_in":3599,"refresh_token":"MASKED","scope":"PSP_AI offline","token_type":"bearer"}

2 * Client out-bound request
2 * 2023-07-04--07:36:33.893+0000
2 > GET https://openbanking.prod.lunar.app/aisp-pisp/accounts
2 > Authorization: Bearer MASKED
2 > Accept: application/json
2 > User-Agent: Tink (+https://www.tink.se/; noc@tink.se)
2 > X-Aggregator: Tink Testing
2 * Client in-bound response
2 * 2023-07-04--07:36:33.893+0000
2 < 404
2 < Cache-Control: must-revalidate,no-cache,no-store
2 < Server: Jetty(9.4.50.v20221201)
2 < Content-Length: 70
2 < Content-Type: application/json
{
"message":"Not Found",
"url":"/aisp-pisp/accounts",
"status":"404"
}

**Comment by Crevil** [comment]
I can find the `oauth2/token` request but the `aisp-pisp/accounts` call doesn't show up in our systems.

I notice the `Server: Jetty(9.4.50.v20221201)` response header. We are not using Jetty so do you request us through any proxy that might interfere with the traffic?

**Comment by Palun** [comment]
Good find! I will see if that can help us troubleshoot
