### ISSUE TITLE
Access Token and AIS-PIS 

### ISSUE THREAD

**Issue by celsomachadotrustly** [lunarway/openbanking#44]
Hello Lunar Team,
We are trying to access the token documentation and seem the page is not working...
URL: https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token.md

Other question:
About the AIS-PIS APIs, Could you confirm the base url? We can't find it in the documentation.
URL: https://developer.openbanking.prod.lunar.app/catalog/default/api/aisp-pisp

We tried using https://tpp.openbanking.prod.lunar.tech, but we received 404 Not Found as an answer.

Thank you!

**Comment by Crevil** [comment]
Documentation on access tokens is located at https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/

Base URLs can be found here: https://developer.openbanking.prod.lunar.app/docs/default/api/registration/#environments

So for AIS-PIS requests an example would be `https://openbanking.prod.lunar.app/aisp-pisp/accounts`
