### ISSUE TITLE
Ping request could not find host test.sandbox.openbanking.prod.lunar.app

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#45]
Hello,
I'm trying to create a new registration with curl but it looks like the server is down. I get: **Could not resolve host: test.sandbox.openbanking.prod.lunar.app**
And when trying to ping test.sandbox.openbanking.prod.lunar.app: **Ping request could not find host test.sandbox.openbanking.prod.lunar.app**

**Comment by Crevil** [comment]
Where did you find that hostname?

The host names are documented in the portal at https://developer.openbanking.prod.lunar.app/docs/default/api/registration

The sandbox hostname is `https://sandbox.openbanking.prod.lunar.app`.

**Comment by milan0v** [comment]
Hi, this is the endpoint for creating test certificates: https://developer.openbanking.dev.lunar.app/docs/default/API/Registration/test_certificates/
![image](https://github.com/lunarway/openbanking/assets/75023012/e53170c5-9e83-4582-a7e5-a8379076525b)

**Comment by Crevil** [comment]
The documentation you are referencing is not out production offering. Please use https://developer.openbanking.prod.lunar.app/ for all Open Banking related documentation.

The certificate issuing feature is no longer available.
