### ISSUE TITLE
Problem with certificates for registration

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#47]
Hello, I tried
curl -v -H "Content-Type: application/json" -X POST --data '{"redirectUris":["https://localhost:5000"],"roles":["PSP_AI","PSP_PI"],"name":"mycompany"}' --cert qwac.crt --key qwac.key https://sandbox.openbanking.prod.lunar.app/tpp
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 52.214.160.186:443...
* Connected to sandbox.openbanking.prod.lunar.app (52.214.160.186) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: Failed to import cert file qwac.crt, last error is 0x80092002
* Closing connection 0
curl: (58) schannel: Failed to import cert file qwac.crt, last error is 0x80092002

Also tried https://tpp.openbanking.prod.lunar.tech/tpp with the same result, any thoughts? And what is the correct url for registering to sandbox ?

**Comment by Crevil** [comment]
This looks to be an issue with the way you are using `curl`. The error message informs you that the certificate is not imported correctly for the request.

```
curl: (58) schannel: Failed to import cert file qwac.crt, last error is 0x80092002
```

This is not something we can assist you with I'm afraid. Please refer to your `curl` versions documentation.

**Comment by Crevil** [comment]
The URL for sandbox is documented here as posted previously another issue as well: https://developer.openbanking.prod.lunar.app/docs/default/api/registration

**Comment by milan0v** [comment]
I had to downgrade my curl version and now I'm getting this:

curl -v -H "Content-Type: application/json" -X POST --data '{"redirectUris":["https://dev-api-symblepay.io/register"],"roles":["PSP_AI","PSP_PI"],"name":"dev-api-symblepay.io"}' --cacert C:/Users/User/Downloads/cacert.pem --cert qwac.crt --key qwac.key https://sandbox.openbanking.prod.lunar.app/tpp

*   Trying 52.209.139.169...
* TCP_NODELAY set
* Connected to sandbox.openbanking.prod.lunar.app (52.209.139.169) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
Enter PEM pass phrase:
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Users/User/Downloads/cacert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=sandbox.openbanking.prod.lunar.app
*  start date: Jun  7 10:56:56 2023 GMT
*  expire date: Sep  5 10:56:55 2023 GMT
*  subjectAltName: host "sandbox.openbanking.prod.lunar.app" matched cert's "sandbox.openbanking.prod.lunar.app"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x256cf7d4110)
> POST /tpp HTTP/2
> Host: sandbox.openbanking.prod.lunar.app
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 104
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
< HTTP/2 400
< date: Thu, 13 Jul 2023 11:27:23 GMT
< content-type: text/html
< content-length: 208
<
<html>
<head><title>400 The SSL certificate error</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The SSL certificate error</center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host sandbox.openbanking.prod.lunar.app left intact
