### ISSUE TITLE
Valid AISP transaction statuses

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#5]
The documentation for `/aisp-pisp/accounts/{accountId}/transactions` [here](https://developer.openbanking.prod.lunar.app/catalog/default/api/aisp-pisp) lists only two values for transaction status:
- future
- financial

While the response for account *6148b3a0-c3e7-4d99-a9bc-985f7decff6c* from sandbox has additional status of `authorization` for a card transaction.

Is this just sandbox having invalid data or there are more transaction statuses possible?

**Comment by dentych** [comment]
The swagger spec has been updated with the statuses that can be returned from the endpoint.
