### ISSUE TITLE
No "ownerName" in /aisp-pisp/accounts response

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#55]
Hello,

We have made tests for Denmark but when getting account information from the `/aisp-pisp/accounts` endpoint we never get the `ownerName` field in the response despite it being stated in your documentation.

In what circumstances do we get this field in the response?

This field is very important to us and without it we cannot use the account for transactions.
Thank you in advance for your help.

**Comment by dentych** [comment]
Hey. Yes, we have a small bug right now that means it isn't sent out. We are working on fixing it 😄

**Comment by dentych** [comment]
This should now be fixed, and account owner name should be part of the GET accounts response 👍
