### ISSUE TITLE
Norwegian accounts always have "supportsPayments: false"

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#56]
Hello,

We have made tests for Norway but when getting account information from the `/aisp-pisp/accounts` endpoint we always get `"supportsPayments": false`, regardless of account. This field seems to be working fine on Denmark but not on Norway. 

Can you verify if the logic for this field is working as expected?

Thank you in advance for your help.

**Comment by dentych** [comment]
Hola! Payments should be supported on Norwegian accounts.

We are quite low on man power until after christmas, so we can first look into fixing this in January.

I have created a task internally for us to look into and fix this after we're back.

**Comment by RafaCMendes** [comment]
Hello! Any updates on this issue?

**Comment by dentych** [comment]
This has now been fixed and the norwegian accounts should have this field set to true
