### ISSUE TITLE
Denmark - HTTP Status 500 when creating domestic transfer

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#57]
Hello,

We have noticed that for Denmark sometimes when creating a domestic transfer we are met with an http status 500 INTERNAL_SERVER_ERROR. Can you help us understand what was the cause for these cases?

- X-Request-ID=**d7c30749-0abb-4740-a0a9-4d5725800d7d** / Timestamp=**2023-12-22T00:58:19.679+01:00**
- X-Request-ID=**4583cbcc-19e9-497c-a0fb-f8995943393c** / Timestamp=**2023-12-22T00:20:58.546+01:00**
- X-Request-ID=**40e53e16-3b16-4180-8b02-b5d9c3b5162a** / Timestamp=**2023-12-21T22:18:11.635+01:00**

Thanks in advance for your help.

**Comment by Crevil** [comment]
Hi 👋 

All three requests were rejected due to the receiver title being too long. It can be at max 20 characters long.
However, I can see that this is not documented in the specification, so we will get that fixed along with mapping the error to a more clear error response to you.

**Comment by Crevil** [comment]
I looked a bit further into our codebase and I can see that this might also be caused by the `message` field exceeding the 20-character limit.

**Comment by facundofederico** [comment]
Please remember to update the documentation regarding the length limit for title

**Comment by facundofederico** [comment]
I'm attempting to start a domestic payment and getting a 500 error.

This is the request:
```
Method: POST, RequestUri: 'https://openbanking.prod.lunar.app/aisp-pisp/payments/domestic-credit-transfer', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  Accept: application/json
  Authorization: Bearer ory_at_R[...]JI
  traceparent: 00-1ec6a5c1552f5c2f5bad3d69b7d8cb67-8ae7d6fe70187de3-01
  Content-Type: application/json
  Content-Length: 273
}
```

This is the body:
```
{
  "redirectUrl": "https://localhost:5011/api/callback/pisp",
  "accountId": "4[...]a",
  "recipientBBAN": "**************",
  "amount": 36.75,
  "currency": "DKK",
  "instant": true,
  "message": "andel - ID: e23d0dc5",
  "title": "e23d0dc5 - Adidas Ca",
  "date": "2024-08-20"
}
```

Both the title and message are 20 characters long.

**Comment by dentych** [comment]
You are attempting to create a transfer with an actorID that does not have access to the account in question.

**Comment by facundofederico** [comment]
I'm sorry, but could you provide more information about that? I:
- Registered my tpp
- Used the id and secret to get an access token
- Used the token to get my account info
- Used that info and a new token to try to initiate a payment

What do you mean by an actorId?
