### ISSUE TITLE
Missing fields in GetTransactions 

### ISSUE THREAD

**Issue by violetaionita-mastercard** [lunarway/openbanking#58]
We have a request from an end user that would like to see the same transactions details as they can in Lunan NetBank. It was identified that on the GetTransactions call the fields “message”(besked) and “fra”(from) are missing. Could you please let me know if these fields are going to be added to the GetTransactions response?

**Comment by dentych** [comment]
Message should already be part of the response if the transfer is a domestic credit transfer.

From is not currently planned to be added.
