### ISSUE TITLE
"UNKNOWN" transfer state

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#59]
Hello,

We have noticed that in Denmark sometimes the transfer state evolves from AWAITING_APPROVAL to UNKNOWN and stays as such for a long period of time to the point our system times out. Here are some examples:

- **X-Request-ID**=5f3e859a-3bd1-4fa9-a08e-f588836827c4 / **Timestamp**=2024-01-10T07:32:18.085+01:00
- **X-Request-ID**=274933bf-8c17-41e0-bf89-b433914b6084 / **Timestamp**=2024-01-10T01:04:13.367+01:00
- **X-Request-ID**=efa93b59-e9cd-4cd9-9c91-4399737e76c0 / **Timestamp**=2024-01-10T01:02:49.982+01:00

We would like to understand better what the UNKNOWN state means because we need to figure out the proper way for us to handle it.

1. Is the UNKNOWN state a final state or will it always move on to another state eventually?
2. Is it possible for the transfer to have been completed and the state being UNKNOWN?
3. Is it possible for the transfer to have been cancelled/rejected/failed and the state being UNKNOWN?

Thanks in advance for your help.

**Comment by dentych** [comment]
We are looking into this. The payment mappings are a bit funky at the moment, so we're looking into improving it.

**Comment by dentych** [comment]
There was a mapping error that has now been fixed. The fix will be deployed to prod in about an hour or so.

The payments were marked as status executing, which turned into "UNKNOWN" in the openbanking API.

**Comment by RafaCMendes** [comment]
Hello @dentych ,

Seems like the issue is still occurring. Here is some examples that happened after your last commet:

**X-Request-ID**=6af6f438-7c64-4364-a77f-48193d6ab973 **timestamp**=2024-02-01T09:55:13.921+01:00
**X-Request-ID**=2b9af5e6-deeb-43e4-91ba-76114f0b3b02 **timestamp**=2024-02-01T09:41:14.819+01:00
**X-Request-ID**=56c8b720-7f3c-488c-be5e-086e97cacd4f **timestamp**=2024-02-01T09:17:20.615+01:00

Can you help us understand what went wrong in these cases?

**Comment by dentych** [comment]
Hey. I did some more mapping of statuses, but it never made it out to prod 🤦 It has now been merged and should be on its way. Sorry for the delay 😬

**Comment by RafaCMendes** [comment]
Hello again @dentych ,

Indeed now we don't get "UNKNOW" status anymore however payment status never seems to move on from "PENDING". We have been unable to complete any transfer because of this. Can you check if there is still an issue with the status mappings?

Best regards,
Rafael Mendes

**Comment by dentych** [comment]
We have an outstanding issue with transfers only getting to pending. It's on our to do to fix, but it has not yet been fixed.

**Comment by dentych** [comment]
We are planning to have it fixed next week

**Comment by RafaCMendes** [comment]
Hello. Why was this ticket closed? 
@dentych Is the fix you mentioned already live?

**Comment by dentych** [comment]
Sorry! I linked this issue with a task on our board, but then closed that task as duplicate because we already had an existing task. Linear took that as "let me close this as not planned" :joy: Sorry for the confusion.

But we are working on implementing a fix for this status issue as we speak 😄 (And I have updated Linear so it won't close this task until it's ACTUALLY done)

**Comment by dentych** [comment]
@RafaCMendes The task to get the payments in correct final states should be done. Can you check if you are seeing this through the openbanking API as well? 🙏

**Comment by RafaCMendes** [comment]
@dentych Yes, seems like it's fixed now. Thank you.
