### ISSUE TITLE
Onboarding fails with timeout

### ISSUE THREAD

**Issue by lucaiia** [lunarway/openbanking#60]
Hello,

We tried to onboard one of our customers to your services, but it failed with timeout as a result. I'm attaching the required information:

1. Certificate chain used during registration: 
**https://keys.nordicapigateway.com/e2c268756efd62191903de4db4499377dd2127ff**

3. Output of the registration call: 
**timeout on POST https://tpp.openbanking.prod.lunar.tech/tpp (2024-01-12T11:15:06.7294191Z)**

Last successful onboarding was done by us at November 13th 2023. Has anything changed since that time?

Best regards,
Lukasz Czaczyk

**Comment by tmablunar** [comment]
Is this still an issue or has the registration been succesful?

**Comment by mzc-lunar** [comment]
Closing stale issue
