### ISSUE TITLE
Sandbox access tokens

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#61]
Hello, 

I have a few questions regarding the access tokens retrieval:
1. Is this the most current documentation: https://developer.openbanking.prod.lunar.app/docs/default/API/Registration/access_token/
2. What is the auth url for sandbox, is it https://sandbox.openbanking.prod.lunar.app/oauth2/auth ?
3. Client secret is not mentioned anywhere in the requests, shouldn't it be used somewhere?

Thanks,
Dimitar

**Comment by Crevil** [comment]
Hi Dimitar,

That is the latest documentation yes.
The auth URL can be found from the details in sandbox at https://auth.sandbox.openbanking.prod.lunar.app/.well-known/openid-configuration. For reference I have added it below and I will ensure it get documented. 

- `https://auth.sandbox.openbanking.prod.lunar.app/oauth2/auth`

As documented in the [Access Token page](https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/) you need to perform an OAuth2 Authorization Code grant with `client_secret_basic`. This is a standard authentication mechanism in the protocol and I will have to refer you to resources elsewhere on how to perform OAuth2.0 and OIDC flows. There are links in the documentation for additional resources that might guide you in the right direction.
