### ISSUE TITLE
[Norway] BBAN error format when creating transfer

### ISSUE THREAD

**Issue by RafaCMendes** [lunarway/openbanking#63]
Hello,

We have made tests for Norway but when trying to create a domestic transfer we receive an http status 422 with the error message "recipientBBAN in body should be at least 14 chars long".  

BBAN in Norway should be 11 characters with IBAN being 15, should it not? In fact, from our tests, when using your API to get account details you use those exact same formats (11-char BBAN and 15-char IBAN).

Can you help us understand what is wrong here? This is blocking us from doing transfers in Norway.

Thank you in advance for your help.

**Comment by dentych** [comment]
Hello.

This is in fact wrong, so we'll deploy a fix. I'll let you know once it's out.

**Comment by dentych** [comment]
This should now be fixed
