### ISSUE TITLE
Sandbox payment wants app approval

### ISSUE THREAD

**Issue by milan0v** [lunarway/openbanking#64]
Hello, 
is there a change in sandbox as of today when I try to make a domestic payment I am sent to this page:
![image](https://github.com/lunarway/openbanking/assets/75023012/8033cb35-e220-4c22-9c26-defc8c50ff3a)
How can this be approved without the app?
Thanks,
Dimitar

**Comment by dentych** [comment]
There is no way to approve the payment in sandbox. The sandbox works entirely with static dummy data, so there's no actual payment being created to approve.

**Comment by milan0v** [comment]
@dentych, how can we test the redirect back to the application that invoked the payment?
