### ISSUE TITLE
GoCardless registration debug 

### ISSUE THREAD

**Issue by DTeivens** [lunarway/openbanking#67]
## Before opening an issue regarding registration problems please ensure that:

-  You are following the documentation at https://developer.openbanking.prod.lunar.app/catalog/default/api/Registration
-  Your certificate chain is valid
- Your intermediate certificate is on the EU Trusted List: https://eidas.ec.europa.eu/efda/tl-browser/#/screen/home

If all the above looks good you can open an issue.

## Required information

**Certificate chain used during registration:**
-----BEGIN CERTIFICATE-----
MIIIXzCCBkegAwIBAgIQWp6kqrIQKLy1aczZtPHT+DANBgkqhkiG9w0BAQsFADCB
ujELMAkGA1UEBhMCSVQxGTAXBgNVBAcMEFBvbnRlIFNhbiBQaWV0cm8xFzAVBgNV
BAoMDkFjdGFsaXMgUy5wLkEuMRowGAYDVQRhDBFWQVRJVC0wMzM1ODUyMDk2NzEp
MCcGA1UECwwgUXVhbGlmaWVkIFRydXN0IFNlcnZpY2UgUHJvdmlkZXIxMDAuBgNV
BAMMJ0FjdGFsaXMgRVUgUXVhbGlmaWVkIENlcnRpZmljYXRlcyBDQSBHMjAeFw0y
MjA4MzExNTM3MDlaFw0yNDA4MzAxNTM3MDlaMIHhMQswCQYDVQQGEwJGUjEOMAwG
A1UECAwFUEFSSVMxDjAMBgNVBAcMBVBBUklTMRcwFQYDVQQKDA5HT0NBUkRMRVNT
IFNBUzEZMBcGA1UEYQwQUFNERlItQUNQUi0xNzExODEXMBUGA1UEBRMOODM0NDIy
MTgwMDAwMzYxFzAVBgNVBAMMDmdvY2FyZGxlc3MuY29tMR0wGwYDVQQPDBRQcml2
YXRlIE9yZ2FuaXphdGlvbjEYMBYGA1UECQwPNyBSVUUgREUgTUFEUklEMRMwEQYL
KwYBBAGCNzwCAQMTAkZSMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
ziw+GFTni+G/ACgRuR4v3jCemnN7qbwSrI8XYCImsBi2jrLUjTbCy0MNZPcW0c9O
gVQ9nz+1qvECGamaiCku60siPHX9I8bKoY+W7w1e7NhqKDBAxdQTs6S1U8LX9Ra3
5wvLYA2PI+q0bwPt45vfV7OJB44f3ePYi0ikw6DQAZrsKvETLBMuq6RppESmYUKk
TgbTYS/aG60Nr861qyeT8rbiN/7uSkA+436QmvY/wiSZkZyYlLbLSshxsz+fKth+
udIaQFKM1RJnUdIoKxjuptaZrLPQKBCRmVZPIw79fbqiLS5HSGXOIXsbs5Xa3sTy
kt5nISHtq6hffYsNryZE2QIDAQABo4IDNjCCAzIwDAYDVR0TAQH/BAIwADAfBgNV
HSMEGDAWgBQiPMtYqC+vziniL9r9DUI11HS6EjCBhQYIKwYBBQUHAQEEeTB3MDsG
CCsGAQUFBzAChi9odHRwOi8vY2FjZXJ0LmFjdGFsaXMuaXQvY2VydHMvYWN0YWxp
cy1laWRhcy1nMjA4BggrBgEFBQcwAYYsaHR0cDovL29jc3AwOC5hY3RhbGlzLml0
L3ZhL2FjdGFsaXMtZWlkYXMtZzIwGgYDVR0SBBMwEYEPaW5mb0BhY3RhbGlzLml0
MBkGA1UdEQQSMBCCDmdvY2FyZGxlc3MuY29tMFsGA1UdIARUMFIwPAYGK4EfDAEB
MDIwMAYIKwYBBQUHAgEWJGh0dHBzOi8vd3d3LmFjdGFsaXMuaXQvYXJlYS1kb3du
bG9hZDAJBgcEAIvsQAEEMAcGBWeBDAEBMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
BgEFBQcDATCCAVMGCCsGAQUFBwEDBIIBRTCCAUEwCAYGBACORgEBMBMGBgQAjkYB
BjAJBgcEAI5GAQYDMIGxBgYEAI5GAQUwgaYwURZLaHR0cHM6Ly93d3cuYWN0YWxp
cy5pdC9kb2N1bWVudGktZW4vcGRzLWZvci1zc2wtc2VydmVyLWFuZC1jb2RlLXNp
Z25pbmcucGRmEwJlbjBRFktodHRwczovL3d3dy5hY3RhbGlzLml0L2RvY3VtZW50
aS1pdC9wZHMtZm9yLXNzbC1zZXJ2ZXItYW5kLWNvZGUtc2lnbmluZy5wZGYTAml0
MGwGBgQAgZgnAjBiMCYwEQYHBACBmCcBAgwGUFNQX1BJMBEGBwQAgZgnAQMMBlBT
UF9BSQwvUHJ1ZGVudGlhbCBTdXBlcnZpc29yeSBhbmQgUmVzb2x1dGlvbiBBdXRo
b3JpdHkMB0ZSLUFDUFIwQAYDVR0fBDkwNzA1oDOgMYYvaHR0cDovL2NybDA4LmFj
dGFsaXMuaXQvdmEvYWN0YWxpcy1laWRhcy1nMi9jcmwwHQYDVR0OBBYEFI0Uurlu
2NgkDIWEMEqaWCXgEH34MA4GA1UdDwEB/wQEAwIFoDANBgkqhkiG9w0BAQsFAAOC
AgEAl0586CefNxjGzt7x17cHSYBbdq/BwL/ShS9JBQPN4BjI3GlKftBUqJ1jRV8g
bkVqz+95PeovnJQCJKWq0gMdvIdhbA50NOUsfddfR+1VFTVZBVTh9ZnFi38No2Yw
jV2vCKj5EyHvsD8zgOZTfOZKE6cncvtMAZg2o1s8SCXu79BpWcpKQHPZcppDmCe3
NkGrBSfLjJmtkGBbd/E0a+rBONYAFsmSX/fkrvgNxiKtJb9++iadt7YZD54e6DNp
XiUTCm6FjeRd308EPvDLEhhjRbInLQLLVvMPWh/cmqqDmjCyamkLRj7XzjTkDc6n
G165YyTNmRFZ8jyJvmbpg6NKEujYmQKpSjq0fNu/mfGCFIW6Uz4t2H+/gG8WcP3Z
pno9ML57kWvTL1o9Lzr2KzM/MCWUtYh+HK2fZh/AbELEIvNitEaiYiVECdTjPo+M
hf1A3Twao9zz+sY1jtpLb8/JCiMe8dqiLtItCNUnLPlQm95jMUpKBBP08BtnkSN1
R7fnaKnIZQrHxLc7NAOI9IzB1DpnAD2hKGZkbdI/PpfY4hA6KorZ98yuaYiecUxf
+CpAeEhEZ3EgwaHbvs5uCo/r7ZfSUETQVGWGygOj2AaP+Y1qeTN0zYw4X+QQ34To
TIQYBDOx8FsbtyOdxXHdo0vlHkQDCVHsIyykLRhT8YzwmoI=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIG1jCCBL6gAwIBAgIILimF6nVQ3qEwDQYJKoZIhvcNAQELBQAwgboxCzAJBgNV
BAYTAklUMRkwFwYDVQQHDBBQb250ZSBTYW4gUGlldHJvMRcwFQYDVQQKDA5BY3Rh
bGlzIFMucC5BLjEaMBgGA1UEYQwRVkFUSVQtMDMzNTg1MjA5NjcxKTAnBgNVBAsM
IFF1YWxpZmllZCBUcnVzdCBTZXJ2aWNlIFByb3ZpZGVyMTAwLgYDVQQDDCdBY3Rh
bGlzIEVVIFF1YWxpZmllZCBDZXJ0aWZpY2F0ZXMgQ0EgRzIwHhcNMTcwOTIyMTQx
NTEzWhcNMzcwOTE3MTQxNTEzWjCBujELMAkGA1UEBhMCSVQxGTAXBgNVBAcMEFBv
bnRlIFNhbiBQaWV0cm8xFzAVBgNVBAoMDkFjdGFsaXMgUy5wLkEuMRowGAYDVQRh
DBFWQVRJVC0wMzM1ODUyMDk2NzEpMCcGA1UECwwgUXVhbGlmaWVkIFRydXN0IFNl
cnZpY2UgUHJvdmlkZXIxMDAuBgNVBAMMJ0FjdGFsaXMgRVUgUXVhbGlmaWVkIENl
cnRpZmljYXRlcyBDQSBHMjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
ALD4lTHZEqhVJPgSKAbtBmV/eBx4PUVpO1JLLkYvvZmcovIatGV6OL06fsdN6gcr
8415MQUhP1Cfgeg+ysjMBhBzK8i8PGPf2H/w2Y7i91yUUscjvtn195+7e6HqvNMK
f0tUxflXq4t3tPeBiSyxLWBWP2ZZ3Z5hBz/kYENxFKKKBYrMjm+SwNw15DTd/xYT
tTQ8lFBXi0vAzQCVSXda8S9YG62w6wYz2tt1pwA8rNIKNyWLLbPCjplb3EK8j4Et
82+Xs4AMEKKgqDYtsCBkYLfQ1MtcMS0OHG/oKK9NoX5rSgEW7R0/HQrvvxOUFBgv
RVQjnXbm9jI/O0gWqZ7DJ8hFRdAD5ko0RewrdHeeqqmd9R0Rll34Jd8OmFTHTEc6
lrjLteVymOkcP5x4/EWzNkG4zUU0Ybt7VycEqmm3hblhnWAeyKSytHp0TfQfw87l
W6oqnO1ruBKE9tyz9doriO66lykVnLEfBDpcpYJNCICAajr8XnDGOXJ+B4Gcn/cN
E/VMcEb5je9wVXTim7Gt7idM40ySw/5CZLALZL3o29fIFPis/yMARL9ysiWxCAmP
JwE+vMDFfVMsED+qFvHLnXJBgMnC4p0pPueLn7qVJyip0h+a5RbNR2jfClmITLGP
sTgJ6hK4hQPyzUX4KfgjpoWkOB/dOJEiqWSnYnfNJ6OFAgMBAAGjgd0wgdowHQYD
VR0OBBYEFCI8y1ioL6/OKeIv2v0NQjXUdLoSMBIGA1UdEwEB/wQIMAYBAf8CAQAw
HwYDVR0jBBgwFoAUIjzLWKgvr84p4i/a/Q1CNdR0uhIwWAYDVR0gBFEwTzBNBgMr
gR8wRjBEBggrBgEFBQcCARY4aHR0cHM6Ly93d3cuYWN0YWxpcy5pdC9yZXBvc2l0
b3J5L2FjdGFsaXMtcXVhbGlmLWNwcy5wZGYwDgYDVR0PAQH/BAQDAgEGMBoGA1Ud
EQQTMBGBD2luZm9AYWN0YWxpcy5pdDANBgkqhkiG9w0BAQsFAAOCAgEARQqwJHLE
ctr3y5RBFA4h0W1NI7BV9YJWesu+BlCkMASBb0svv1S5DPsqLKzVXSlWawZ3uURk
IuhzIrBLkYGEr0sQ4cirnTxIPvlTIPGBGK+a8iXfcH5RvtYAHL2yEqRuLPW9Bm3B
yBeBYWaX1un1F7GsV08DhmAtDkwicj4egbW/C3wmvYISHAM9YXdvUXV5e6FsZ+nq
adlnRHKP5RdSRJzUi9svvzBGuNpvcnsq6gA9y/swFxdRLUaPaUCgcDet0FRGrAk2
igq3eWtxReJxk2vPzDZULdLvBeKuC/4BId8mS6Va7KI8mBFi+sa3cTsNP26Y5ioL
rtB46nQnBBLNXZrYWLmw8TZlbeTdnnQnb6IB9ODNzT5bmNL/D2WnFFH1ueigC8Ir
RIjVZipFuWtD02v1BSCupQvpmjimrd6HKQKCf3HUbbAvXeMJP7vs7SfKKboYtUhE
/TcLvMAnqKTfieFd0rVDmwA85vQqefiFQ3VqYZeTyHzZui7r8d4jbdMm9ZlWWhF+
7YEPGNErMGc025RdeEmLMoQo8TWyV01grZwQUEhsBEZ1O9drKFnQWZ7XcFaVBk7e
u4tpZe7+Xr/oDG0yAberZP9yaX8z9quyi3m07IRCTmLiSOywFMo58iYmxkpi/8VS
uAou9el/cliMUmY5HJoavpyojGKF4EOchcI=
-----END CERTIFICATE-----

**Output of the registration call:**
* LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C418:SSL routines:ST_OK:tlsv1 alert unknown ca, errno 0
* Failed receiving HTTP2 data: 56(Failure when receiving data from the peer)
* Connection #0 to host tpp.openbanking.prod.lunar.tech left intact
curl: (56) LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C418:SSL routines:ST_OK:tlsv1 alert unknown ca, errno 0
**Time of the registration request:**
15:25 GMT+2
**Link to the intermediate certificate on the [EU Trusted list](https://eidas.ec.europa.eu/efda/tl-browser/#/screen/home):**
https://eidas.ec.europa.eu/efda/tl-browser/#/screen/tl/IT/3/71
**Debug information**

* Call `https://debug.openbanking-sandbox.prod.lunar.tech` including your full certificate chain and private key (eg. `curl https://debug.openbanking-sandbox.prod.lunar.tech --cert your_full_certificate_chain.pem --key your_private_key.pem`) 
* Note the time of the call:
< date: Tue, 20 Feb 2024 13:37:30 GMT - **this is returned timestamp in response** 
---

Please ensure that all information has been checked and are valid!

Issues with missing information will be closed.

**Comment by nixboot** [comment]
Hi @DTeivens :wave:

Thanks for the great level of detail you provided.

We have looked into you issue, and have adjusted a couple of things in our end. 

Can I get you to retry your registration request?

**Comment by DTeivens** [comment]
Hello @nixboot 
Looks like registration request went through successfully, got Id and secret in response.
Thanks a lot for your help on this one

**Comment by nixboot** [comment]
🙌  glad to hear.
