### ISSUE TITLE
Support for TLS v1.2

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#7]
Hi,
we asked over a week ago to loosen the TLS version requirement to allow TLS 1.2 with some secure cipher suites as well and got a response that it will be changed immediately.
What is the status of that?
Can we expect the change to be done soon?

**Comment by hoeg** [comment]
Hi,
we are working on this issue but unfortunately we cannot promise a date where it will be done. We will update this issue once the fix is deployed.

**Comment by hoeg** [comment]
Hi @mbospiir, we have released a fix that enables TLSv1.2. I will close this issue now. You are always welcome to open a new issues if you are experiencing any difficulties.
