### ISSUE TITLE
Question about Initiate Payment body 

### ISSUE THREAD

**Issue by DTeivens** [lunarway/openbanking#70]
I started to work on PIS flow and got few questions there.
for payment initiation i have to use this body :
{
"redirectUrl": "string",
"accountId": "string",
"recipientBBAN": "stringstrin",
"amount": 0,
"currency": "string",
"instant": true,
"message": "string",
"title": "string",
"date": "2024-02-26"
}

So if i understand correctly then "recipientBBAN" is creditors account IBAN?
and "accountId" is debtors account_id?
 From the response bodies structure in /get payment details "accountId" looks like resources_id, and since that id is a mandatory field i have another question , dose user can obtain such id through mobile app for example or is there any other way around to get it ?

**Comment by dentych** [comment]
Hello.

Apologies for the late reply.

I assume you are talking about the domestic credit transfer flow, as the request body you pasted looks identical to that.

The recipientBBAN is the receipient's/creditor's BBAN, not the IBAN.

The accountId is retrieved from the `id` field of the `GET /aisp-pisp/accounts` response. (https://developer.openbanking.prod.lunar.app/catalog/default/api/aisp-pisp)

The user can not obtain the account ID from the app.
