### ISSUE TITLE
500 Internal Server Error - Trustly

### ISSUE THREAD

**Issue by frankfranque** [lunarway/openbanking#71]
Hello guys, I'm Frank from Trustly. We have implemented your API. However, since yesterday we are receiving **500 Internal Server Error** response when try to get the accounts. Could you help us solve the issue?

Best regards

```
X-Request-ID=362da752-7d7a-4f1a-968a-17d20518ab82

body=<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
</body>
</html>
```

**Comment by dentych** [comment]
Hello.

We are currently investigating and will give you an update once we know more

**Comment by frankfranque** [comment]
Thank you

**Comment by dentych** [comment]
Hey @frankfranque . We've looked into the case and solved an issue with auth server. We're seeing many more calls going through now. Can you please try again and see if the issues you had are also resolved?

**Comment by frankfranque** [comment]
Hello @dentych, the issue is resolved. 
Thank you for you assistance.
