### ISSUE TITLE
About certificate change

### ISSUE THREAD

**Issue by DTeivens** [lunarway/openbanking#74]
Hello!

I am reaching out to you as a representative of GoCardless, concerning a few questions we have regarding the integration with your bank's PSD2 API. At GoCardless, we highly value the seamless and uninterrupted access to connected accounts, balances, and transactions for our clients. Therefore, we would appreciate clarification on the following matters:

1.Do we lose access to connected accounts when certificates are changed? Specifically, if we connect an account using certificate A and start using certificate B, will we still be able to retrieve data from the accounts connected with certificate A using the new set of certificates B?

2.Does your API support multiple production applications with different certificates for a single Third Party Provider? Our intention is to continue using our existing application with certificate A, while simultaneously creating another application with certificates B to connect accounts with.

If neither of the above scenarios is feasible, we would like to explore alternative solutions that ensure uninterrupted access to accounts. Do you have alternative options to ensure uninterrupted access?

We greatly appreciate your assistance and guidance in addressing these questions. Your prompt response will contribute to a smoother integration process for our mutual clients.

Thank you for your attention to this matter. We look forward to hearing from you soon.

Kind regards,
Dāvis T

**Comment by nixboot** [comment]
Hi Dāvis. Thanks for reaching out.

> 1. Do we lose access to connected accounts when certificates are changed? Specifically, if we connect an account using certificate A and start using certificate B, will we still be able to retrieve data from the accounts connected with certificate A using the new set of certificates B?

If the issuing certificate for certificate B is the same from certificate A, you will not lose access.

If the issuing certificates differ, you need to make a TPP registration using certificate B before doing the switch.

> 2. Does your API support multiple production applications with different certificates for a single Third Party Provider? Our intention is to continue using our existing application with certificate A, while simultaneously creating another application with certificates B to connect accounts with.

Yes, it is possible to have two registrations and use them simultaneously.

I hope this information helps you move forward with your project.

**Comment by nixboot** [comment]
As this issue has been quiet for a while, I'll assume my answer was sufficient and close it.

Feel free to open a new issue, if you have any more questions.
