### ISSUE TITLE
Lunar PSD2 API specs in SE (not a bug)

### ISSUE THREAD

**Issue by duartelorvaotrustly** [lunarway/openbanking#75]
Hello, Lunar PSD2 API team,

I have a few questions about the PSD2 API that Lunar has available for Sweden (SE).

In order for the end user to log in, an identification number is required. Is this the Social Security Number (SSN) in SE? If so, does the API return that value to the TPP through some response? If not, are there plans to start doing so?

Also, what authentication methods are available through the Lunar PSD2 API in SE? Are they just Lunar-specific authentication methods? Or is BankID also available? If BankID is available, is it only through a redirect flow or also through a decoupled flow?

Thank you.

Best regards,
Duarte Lorvão

**Comment by duartelorvaotrustly** [comment]
Hello, Lunar PSD2 API team,

Did you have time to see my message above?

Thank you.

Best regards,
Duarte Lorvão

**Comment by AndersSoee** [comment]
Hi Duarte Lorvão

The identification number is the SSN, yes.
Wo do not currently expose the SSN in the api, and there are no plans of doing so either.

The only authentication method supported, is approval in the Lunar app.

Kind regards,
Anders

**Comment by duartelorvaotrustly** [comment]
Hi, Anders,

Thanks for your reply.

Best regards,
Duarte Lorvão
