### ISSUE TITLE
Redirecting in sandbox and production

### ISSUE THREAD

**Issue by naurisSeglins** [lunarway/openbanking#79]
Hello,
I wanted to clarify about redirecting when making payments.

When creating payment there is the 1st redirect to authorize so that access token can be created.
2nd redirect link is once the payment request is made.

Here is example:
/aisp-pisp/payments/domestic-credit-transfer HTTP/1.1
Content-Length: 258
Authorization: Bearer ory****Vry4
X-Request-ID: 52666519-d154-4fc3-8b76-1c30c976fd67
Content-Type: application/json

{
    "redirectUrl": "https://ob.gocardless.com/psd2/pis/processing/4fd85eab-4a47-452e-aac1-41c0db62afdb/LUNAR_SANDBOX_LUNADK22",
    "accountId": "6148b3a0-c3e7-4d99-a9bc-985f7decff6c",
    "recipientBBAN": "66952000000001",
    "amount": 10,
    "currency": "DKK",
    "message": "hope this"
}, 
psd2_response_debug=HTTP/1.1 200 OK
Date: Wed, 14 Aug 2024 10:11:48 GMT
Content-Type: application/json
Content-Length: 212
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Proxygen-Request-Success: true
X-Postigen-Response-URL: https://sandbox.openbanking.prod.lunar.app/aisp-pisp/payments/domestic-credit-transfer

{
    "authUrl": "https://auth.sandbox.openbanking.prod.lunar.app/aisp-pisp/polling?paymentID=6bf6ad0c-a4cd-4f4c-a141-8c82257aa734&initiateTime=2024-08-14T10:11:48Z",
    "paymentId": "6bf6ad0c-a4cd-4f4c-a141-8c82257aa734"
}.

authUrl redirects to the page that asks to open the app:
<img width="781" alt="Screenshot 2024-08-14 at 13 14 22" src="https://github.com/user-attachments/assets/2e9f0145-93ff-4a36-b4f7-8ab1327a1d55">

but once redirected to this link we are not redirected back. In your documentation it is written that 
> The supplied redirect_url will be ignored, and the payment initiation auth webview will always redirect back to https://lunar.app

I want to clarify that:
Do we need to redirect PSU to the authUrl for them to see the message and time or they should know this themselves?
Is this expected that in sandbox we are not redirect back to our redirect_url?
Will the redirect to our page work in production?

If the questions don't make sense or aren't understandable could you please write the expected flow for authorization and payment creation and handling?

Best regards,
Nauris

**Comment by AndersSoee** [comment]
Hi.

> Do we need to redirect PSU to the authUrl for them to see the message and time or they should know this themselves?

Yes, you should redirect to the authUrl.

> Is this expected that in sandbox we are not redirect back to our redirect_url?

Yes, a side effect of the sandbox only having static data, is that the payment will "stay" in awaiting approval state.

> Will the redirect to our page work in production?

Yes it will.

Hope this helps.
/Anders

**Comment by nixboot** [comment]
Hi. We haven't heard back from you on this issue in a while, so we will close it for now. If you have any further questions or information, please feel free to reopen this issue or create a new one. Thanks!
