### ISSUE TITLE
Prod onboarding fails

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#8]
Hi,
thanks to TLS v1.2 being enabled, we could try the production API.
It unfortunately fails during onboarding with:
```
------- Request -----------
POST https://openbanking.prod.lunar.app/tpp/register
Host: openbanking.prod.lunar.app
X-Request-Id: 854d6c0d-9cd6-49a6-8e3e-cc4a0306f28a
Accept: application/json
Content-Type: application/json
Transfer-Encoding: chunked

{
    "roles": [
        "PSP_AI",
        "PSP_PI"
    ],
    "redirectUris": [
        "SOME_URI"
    ]
}
------- Response -----------
Status: 400
Date: Tue, 21 Sep 2021 12:05:18 GMT
Content-Type: text/html
Content-Length: 208
Connection: close

<html>
<head><title>400 The SSL certificate error</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The SSL certificate error</center>
<hr><center>nginx</center>
</body>
</html>
```

Can you investigate the cause of it? Sandbox onboarding works just fine with a sandbox certificate.

**Comment by hoeg** [comment]
Did you use mTLS for the registration request as done in the example provided here: https://developer.openbanking.prod.lunar.app/docs/default/api/registration/register/

**Comment by mbospiir** [comment]
Yes, I did use MTLS. Also the QWAC is issued by a QTSP - https://webgate.ec.europa.eu/tl-browser/#/tl/NO/1/3

**Comment by hoeg** [comment]
@mbospiir is your certificate issued directly by https://webgate.ec.europa.eu/tl-browser/#/tl/NO/1/3 or are there any intermediate certificates in play?

**Comment by mbospiir** [comment]
@hoeg directly by Buypass Class 3 CA G2 QC WA

**Comment by hoeg** [comment]
@mbospiir would you be able to providers with the details of your process of registrating (of course without your cert and private key) so that we can try and reproduce the issue?

**Comment by mbospiir** [comment]
@hoeg could you please contact me by email at mbo (at) aiia.eu, so I can provide you with more details?
