### ISSUE TITLE
Denmark PSD2 - Invalid client after approving the notification in the bank application

### ISSUE THREAD

**Issue by JavierGalileaBrite** [lunarway/openbanking#85]
Hello,

I'm trying to get the access token following the flow described [here](https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/).

1. I start the Oauth2 authorization code grant with this request
```
SEND Method=POST 
URL=https://auth.openbanking.prod.lunar.app/oauth2/auth 
Body=b'response_type=code&client_id=********&redirect_uri=https%3A%2F%2Fintegration-callback.production.britepayments.io%2Fv1%2Fcallback%2Fredirect&scope=PSP_AI+PSP_PI&state=935f9edc-44b0-4649-ab43-4730b1d66df8' 
Headers={}
``` 

2. The customer is redirected to this url and enter his ssn in this screen
```
https://auth.openbanking.prod.lunar.app/connect/connect?login_challenge=49c2313fedb04a25a9508795055bb618
``` 

![image](https://github.com/user-attachments/assets/290ee473-13e6-4819-a71f-1e3a4261ed81)

3. The customer accept the push notification in his bank app

4. Then I get this error url
```
https://auth.openbanking.prod.lunar.app/oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29.+The+requested+OAuth+2.0+Client+does+not+exist.
``` 

![image](https://github.com/user-attachments/assets/6ee13c7e-4f2a-43e7-af88-b932d7c3d032)

Any clues as to what may be happening here?

Thanks in advance!!

**Comment by AndersSoee** [comment]
Are you including the correct client_secret basic authentication here?:
<img width="525" alt="image" src="https://github.com/user-attachments/assets/50acfa2f-2e4a-4bca-8d3b-a43f8d123d75">

**Comment by JavierGalileaBrite** [comment]
I haven't reached this step yet, I'm getting the error in this last redirect so I haven't yet been able to get the authorization code yet
![image](https://github.com/user-attachments/assets/fd8be455-371b-4455-8759-1bf9313cef13)

**Comment by JavierGalileaBrite** [comment]
The redirected url was not the right one
