### ISSUE TITLE
Missing scope after registration

### ISSUE THREAD

**Issue by evahteri** [lunarway/openbanking#86]
Hello Lunar,

We recently onboarded our customer Qred Bank AB to the production environment. We are facing an issue where the authorization url is producing the following redirect: https://eb.qred.com/ais/?error=invalid_scope&error_description=The%20requested%20scope%20is%20invalid,%20unknown,%20or%20malformed.%20The%20OAuth%202.0%20Client%20is%20not%20allowed%20to%20request%20scope%20%27tpp%3Awrite%27.&state=6b8e7f2c-965d-4861-a273-eb5ca0183c38. Earlier the tpp:write scope was included after registration. How can we update the application to include this scope? Thank you for your assistance.

Best regards,

Eero Vahteri
eb@qred.com

**Comment by mzc-lunar** [comment]
Hi

`tpp:write` is not a valid scope for our API according to our docs, which you can read [here](https://developer.openbanking.prod.lunar.app/docs/default/api/registration/access_token/#scopes). I suggest you have a read at the docs and get back to us if you still have questions 🙂
