### ISSUE TITLE
HTTP Error 500 creating payment

### ISSUE THREAD

**Issue by JavierGalileaBrite** [lunarway/openbanking#87]
I'm having some errors creating the payment, I used this post

```
SEND Method=POST 
URL=https://openbanking.prod.lunar.app/aisp-pisp/payments/domestic-credit-transfer 
Body={
   "accountId":"80****17-0**6-4**e-8**2-bb********4c",
   "amount":1.0,
   "currency":"dkk",
   "date":"2024-10-17",
   "instant":true,
   "message":"RF8020000001FA6502",
   "recipientBBAN":"89000000703587",
   "redirectUrl":"https://integration-callback.production.britepayments.io/v1/callback/redirect",
   "title":"RF8020000001FA6502"
}
Headers={'Authorization': 'Bearer ory_at_2++IqGRMuxS_cVU', 'Content-type': 'application/json'}
```

And I get this error
`HTTP Error 500: Internal Server Error, Retrying in 3 seconds...`

In sandbox env seems to work fine.

Do you know what can be happening here? Thanks in advance!

**Comment by JavierGalileaBrite** [comment]
I'm sorry to tag all of you here but do you have any clue on that issue? @runehammerskov @hoeg @mrjensen @dentych

**Comment by runehammerskov** [comment]
Validation fails with `field 'Currency': 'dkk' is an invalid currency`. It should be upper case, so `DKK`.

**Comment by JavierGalileaBrite** [comment]
Thanks! I could post the payment and the customer get his money debited but I get this
