### ISSUE TITLE
Question about pagination

### ISSUE THREAD

**Issue by DTeivens** [lunarway/openbanking#88]
Hello!
Is there a way to see how many transactions will be returned in specific time period?
Or is there any other way to distinguish how many request i need to make until i receive all transactions for specific time period ?
If there is no such thing , what happens at that point were i request transactions an there is nothing to return, is there an empty response body?

**Comment by mathies1988** [comment]
Hi there.

1. The only way to figure how many transactions is returned in a specific time period is to page through the transactions in the period and count them.
2. There is no way to determine this, other than paging through the time period.
3. You should be able to test this by querying for a time period that you know do not have any transactions. When looking at the code it should simple return an empty response.

**Comment by eprieditis** [comment]
hello,could you please show us an example of how would transactions response look if there are on transactions?

would it be like an empty list like this?

{
    "from": "2024-11-24T00:00:00.000Z",
    "limit": 100,
    "to": "2025-02-21T00:00:00.000Z",
    "transactions": []
}

Thanks!

Kind regards,
Elvis
