### ISSUE TITLE
[QUESTION] API features

### ISSUE THREAD

**Issue by cryptobench** [lunarway/openbanking#89]
I been unable to find answers on this from the phone support or the API docs.

Is it possible to 

1) Create accounts (konti) via the API?
2) Is it possible to create bank transfers via the API to people outside lunar?
    2.1 ) I saw something about accountID but is that possible to create via the API?
    
    
    I basically want to use an API to create x kontier for my clients, and then at the end of the month pay out their earnings via the API. Is that possible via the API?

**Comment by dentych** [comment]
Please see the spec here:
https://developer.openbanking.prod.lunar.app/catalog/default/api/aisp-pisp

1. No
2. Yes

**Comment by dentych** [comment]
Domestic credit transfers are made with accountID for the sender account (which is the Lunar customer) and a recipient BBAN for the receiver (the person with a bank account outside of Lunar).

**Comment by cryptobench** [comment]
Thank you @dentych . I have looked through the OpenAPI spec, but its using banking lingo which is not obvious to me thus I reached out here after an unsuccessful attempt via the phone support.


I haven't heard about BBAN before, but from what I read it's essentially the last 14 characters of the IBAN number - correct?


Secondly, are there any other more optimal ways of managing kontis via the API? I'm just wondering what the benefit of unlimited kontis on the limitless plan is, if I can't optimally use it.

**Comment by dentych** [comment]
BBAN and IBAN are internationally recognized terms that have plenty of documentation online. This is a banking API and as such will use banking terms. The BBAN is the country local bank account number.

Managing accounts is not the purpose of the the openbanking API. It's satisfying the EU PSD2 legislation (Payment Services Directive). That means viewing accounts and balances + making transfers/payments.
