### ISSUE TITLE
Company name extracted from the certificate

### ISSUE THREAD

**Issue by mbospiir** [lunarway/openbanking#9]
Hi,
it seems that you automatically extract the company name from the QWAC and then use it in the redirect flow.
The problem is it's not the `Organization (O)` property but `2.5.4.97`.
This results in the following - the end-user sees TPP id and not a company name.
![Screenshot 2021-10-20 at 11 16 46](https://user-images.githubusercontent.com/75615254/138065956-021ecd16-4b4d-4c85-bea5-3d05b9885c09.png)

Can you please try to use the `Organization (O)` first and then fallback to the currently used property?
If it happens only once during onboarding, we would like to change this name for our clientId.

**Comment by bsnlunar** [comment]
Hi Mbospiir 
This issue is now placed into the backlog we have no current time for resolving the issue

**Comment by hoeg** [comment]
@mbospiir we have pushed a change that should fix this issue. Let me know if anything is not as expected 🚀
